name: GitHub Actions
run-name: Build, test and delivery to pre-produbtion env 
on: [push]
jobs:
  Build-Test-Publish:
    runs-on: ubuntu-20.04 
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: docker build -t tomkatzav/argo-weather:1.0.${{ github.run_number }} ./app
      - run: docker run -p 5000:5000 --name=argo-weather -d tomkatzav/argo-weather:1.0.${{ github.run_number }}
      - run: pip install -r ./app/requirements.txt
      - run: python3 ./tests/unit_test.py
      - run: python3 ./tests/docker_image_test.py
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker push tomkatzav/argo-weather:1.0.${{ github.run_number }}

  Update-Push: 
    needs: Build-Test-Publish
    runs-on: ubuntu-20.04 
    steps:
      - run: git clone https://github.com/tomKatzav96/Pre-Prod-Argo-Project.git
      - run: sed -i '8 s/1.0.[1-9][1-9]/1.0.${{ github.run_number }}/' ./Pre-Prod-Argo-Project/values.yaml
      - name: Commit files
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          cd Pre-Prod-Argo-Project
          git config --global user.email "tom.katzav@gmail.com"
          git config --global user.name "tomKatzav96"
          git commit -a -m "push to pre-prod"
          git remote remove origin
          git remote add origin git@github.com:tomKatzav96/Pre-Prod-Argo-Project.git
          git push https://"$GITHUB_ACCESS_TOKEN"@github.com/tomKatzav96/Pre-Prod-Argo-Project.git

          