name: GitHub Actions
run-name:  continuous integration and delivery to pre-produbtion env 
on: [push]
jobs:
  Build-Test-Publish:
    runs-on: ubuntu-20.04 
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: docker build -t tomkatzav/argo-weather:1.0.${{ github.run_number }} ./app
      - run: docker run -p 5000:5000 --name=argo-weather -d tomkatzav/argo-weather:1.0.${{ github.run_number }}
      - run: pip install -r ./app/requirements.txt
      - run: python3 ./tests/unit_test.py
      - run: python3 ./tests/docker_image_test.py
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker push tomkatzav/argo-weather:1.0.${{ github.run_number }}

  Update-Push: 
    needs: Build-Test-Publish
    runs-on: ubuntu-20.04 
    steps:
      # - name: Check out repository code
      #   uses: actions/checkout@v3
      - run: git clone https://github.com/tomKatzav96/Pre-Prod-Argo-Project.git
      - run: cat ./Pre-Prod-Argo-Project/values.yaml
      - run: sed -i 's/VERSION_NUMBER/1.0.${{ github.run_number }}/' ./Pre-Prod-Argo-Project/values.yaml
      - run: cat ./Pre-Prod-Argo-Project/values.yaml
      - name: Commit files
        run: |
          cd Pre-Prod-Argo-Project
          git commit -a -m "push to pre-prod"
          git remote remove origin
          git remote add origin git@github.com:tomKatzav96/Pre-Prod-Argo-Project.git
          git push -u origin main
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}
